# Generated by Django 5.1.3 on 2024-11-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_pollsuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollsUser',
        ),
    ]
